#!/bin/bash

echo "⚠️  AVISO SOBRE SINCRONIZAÇÃO DE TEMPO"
echo "======================================"
echo ""
echo "🔍 STATUS ATUAL:"
echo "   • Métricas Kong: ✅ FUNCIONANDO"
echo "   • Prometheus queries: ✅ FUNCIONANDO" 
echo "   • Grafana dashboards: ✅ FUNCIONANDO"
echo "   • Sincronização de tempo: ⚠️ WARNING (mas não crítico)"
echo ""
echo "💡 EXPLICAÇÃO:"
echo "   O warning 'Server time is out of sync' no Prometheus é um problema"
echo "   comum do Podman no macOS. Isso acontece porque:"
echo "   • Containers usam tempo interno diferente do host"
echo "   • macOS não compartilha timezone automaticamente"
echo "   • Podman tem limitações de sincronização temporal"
echo ""
echo "✅ IMPORTANTE:"
echo "   • As métricas continuam funcionando PERFEITAMENTE"
echo "   • Queries temporais (increase, rate) estão OK"
echo "   • Dashboards mostram dados corretos"
echo "   • É apenas um aviso cosmético"
echo ""
echo "🎯 PARA APRESENTAÇÃO:"
echo "   1. Ignore o warning amarelo no Prometheus"
echo "   2. Foque nos dashboards do Grafana"
echo "   3. As métricas são precisas e funcionais"
echo "   4. Explique que é uma limitação do ambiente de dev"
echo ""
echo "🔧 SOLUÇÃO EM PRODUÇÃO:"
echo "   • Use Docker ao invés de Podman"
echo "   • Configure NTP nos containers"
echo "   • Use Kubernetes para melhor gerenciamento"
echo "   • Configure timezone compartilhado"
echo ""
echo "📊 TESTE AGORA:"
echo "   • Grafana: http://localhost:3000 (admin/admin123)"
echo "   • Prometheus: http://localhost:9090 (ignore warning)"
echo "   • Gere tráfego: ./simple-load-test.sh"
echo ""

# Gerar tráfego para mostrar que funciona
echo "🚀 Gerando tráfego de teste..."
./simple-load-test.sh > /dev/null 2>&1

echo ""
echo "📈 MÉTRICAS ATUAIS:"
TOTAL=$(curl -s "http://localhost:9090/api/v1/query?query=sum(kong_http_requests_total)" | jq -r '.data.result[0].value[1]' 2>/dev/null)
RATE=$(curl -s "http://localhost:9090/api/v1/query?query=sum(rate(kong_http_requests_total%5B5m%5D))" | jq -r '.data.result[0].value[1]' 2>/dev/null)
echo "   • Total requests: $TOTAL"
echo "   • Current rate: $RATE req/s"
echo ""
echo "✅ TUDO FUNCIONANDO! Warning é apenas cosmético."
